
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t dahlyanini1/resume2 .
      - name: Push image 
        run: |
            docker login -u dahlyanini1 -p ${{secrets.REGISTRY_PASS}}
            docker push dahlyanini1/resume2
             